mybatis:
    mapper-locations: classpath:mappers/*xml
    type-aliases-package: com.woniu.entity
server:
    port: 8080
spring:
  application:
        name: object-his
  datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://192.172.0.201:3306/his?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  level:
    com:
      woniu:
        mapper: debug